Feature: Translation compare page

    Background: I am on translation compare page
        Given I open the website "/services/translation/compare-plans"

    @sanity
    Scenario Outline: I expect that all links on translation compare page should be verified against expectation
        Then I expect that element <element> has the link <link>
        @chn
        Examples:
            | element                                                      | link                                  |
            | //*[@id="serviceOptions"]/app-options-ruby/div[1]/app-lynk/a | "/services/translation"               |
            | //*[@id="serviceOptions"]/app-options-ruby/div[2]/app-lynk/a | "/services/translation/AI"            |
            | //*[@id="serviceOptions"]/app-options-ruby/div[3]/app-lynk/a | "/services/translation/professional"  |
            | //*[@id="serviceOptions"]/app-options-ruby/div[4]/app-lynk/a | "/services/translation/upgraded"      |
            | //*[@id="serviceOptions"]/app-options-ruby/div[5]/app-lynk/a | "/services/translation/compare-plans" |

        @jpn
        Examples:
            | element                                                                   | link                                                          |
            | //*[@id="serviceOptions"]/app-options-ruby/div[1]/app-lynk/a              | "/services/translation"                                       |
            | //*[@id="serviceOptions"]/app-options-ruby/div[2]/app-lynk/a              | "/services/translation/standard-translation-plan"             |
            | //*[@id="serviceOptions"]/app-options-ruby/div[3]/app-lynk/a              | "/services/translation/premium-translation-plan"              |
            | //*[@id="serviceOptions"]/app-options-ruby/div[4]/app-lynk/a              | "/services/translation/top-journal-translation-plan"          |
            | //*[@id="serviceOptions"]/app-options-ruby/div[5]/div/ul/li[1]/app-lynk/a | "/services/translation/basic-translation-plan"                |
            | //*[@id="serviceOptions"]/app-options-ruby/div[5]/div/ul/li[2]/app-lynk/a | "/services/other/book-translation-and-editing"                |
            | //*[@id="serviceOptions"]/app-options-ruby/div[5]/div/ul/li[3]/app-lynk/a | "/services/translation/english-to-japanese"                   |
            | //*[@id="serviceOptions"]/app-options-ruby/div[5]/div/ul/li[4]/app-lynk/a | "/info/ppc/thesis-translation"                                |
            | //*[@id="serviceOptions"]/app-options-ruby/div[6]/div/ul/li[1]/app-lynk/a | "/pricing/translation-service"                                |
            | //*[@id="serviceOptions"]/app-options-ruby/div[6]/div/ul/li[2]/app-lynk/a | "/services/translation/compare-plans"                         |
            | //*[@id="serviceOptions"]/app-options-ruby/div[6]/div/ul/li[3]/app-lynk/a | "/quality"                                                    |
            | //*[@id="serviceOptions"]/app-options-ruby/div[6]/div/ul/li[4]/app-lynk/a | "/services/translation/japanese-to-english/sample"            |
            | //*[@id="serviceOptions"]/app-options-ruby/div[6]/div/ul/li[5]/app-lynk/a | "/subject-expertise"                                          |
            | //*[@id="header"]/section/div/app-navigator[2]/div/ul/li[4]/app-lynk/a    | "/order/ncf/translation-services?ss=j2e&pd=js&source=website" |

        @pending-kor
        Examples:
            | element                                                                                 | link                                                                      |
            | //*[@id="serviceOptions"]/app-options/app-lynk[1]/a                                     | "/services/translation"                                                   |
            | //*[@id="serviceOptions"]/app-options/app-lynk[2]/a                                     | "/services/translation/standard-translation-plan"                         |
            | //*[@id="serviceOptions"]/app-options/app-lynk[3]/a                                     | "/services/translation/premium-translation-plan"                          |
            | //*[@id="serviceOptions"]/app-options/app-lynk[4]/a                                     | "/services/translation/compare-plans"                                     |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[21]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/standard-translation?source=website" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[21]/div[3]/app-lynk/a | "/order/ncf/j2e-translation-services/premium-translation?source=website"  |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[21]/div[4]/app-lynk/a | "/order/ncf/j2e-translation-services/japan-tl-plus-scientific-editing"    |

    Scenario Outline: I expect to see correct pricing for all translation compare page
        Then I expect that element <element> matches the text <price>

        @chn
        Examples:
            | element                                                                 | price         |
            | //app-compare-block-information[1]//span[contains(@class,'text-2.5xl')] | "￥0.45/字 起" |
            | //app-compare-block-information[2]//span[contains(@class,'text-2.5xl')] | "￥0.65/字 起" |
            | //app-compare-block-information[3]//span[contains(@class,'text-2.5xl')] | "￥1.01/字 起" |

        @pending-kor
        Examples:
            | element                                                                                                                       | price    |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[1]/div/div/span[2]         | "11.7円" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[2]/div/div/span[2]         | "11円"   |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[3]/div/div[3]/span[2]      | "27円"   |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[1]/div/div/span[1]/span    | "14.3円" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[2]/div/div/span[1]/span    | "22.0円" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[3]/div/div[3]/span[1]/span | "46.2円" |

    @sanity
    Scenario Outline: I expect to open order page on forms on clicking on forms CTA on compare translation page
        Then I expect that element <path> has the link <link>
        When I click on the element <path>
        Then I expect that element <eosElementPath> has the class <eosElementClass>
        And I should go back to the previous page

        @chn
        Examples:
            | path                                                                                    | link                                                                                                            | eosElementPath                                                                                                                                                             | eosElementClass    |
            | //*[@id="header"]/section/div/app-navigator[2]/div/ul/li[8]/app-lynk/a                  | "/order/ncf/translation-services?source=website"                                                                | /html/body/app-root/ng-component/div/section/div/ng-component/ng-component/div/div[2]/div/div[1]/table/tbody/tr[4]/td[2]/button                                            | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[20]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-level-1?source=website"                          | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-document/div/section/div[1]/div[1]/div[1]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[20]/div[3]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-standard-editing?source=website"     | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-document/div/section/div[1]/div[1]/div[1]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[20]/div[4]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing-plus?source=website" | //*[@id="field_file_upload_order"]/div/div[1]/div[1]/div                                                                                                                   | "btn-primary-blue" |
        @jpn
        Examples:
            | path                                                                                    | link                                                                      | eosElementPath                                 | eosElementClass    |
            | //*[@id="header"]/section/div/app-navigator[2]/div/ul/li[4]/app-lynk/a                  | "/order/ncf/translation-services?ss=j2e&pd=js&source=website"             | *//ul[@class ="tc-table"]/li[1]//h3            | "tc-head-text"     |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[21]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/standard-translation?source=website" | //*[@id="prospect"]/div/div/div/div/div/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[21]/div[3]/app-lynk/a | "/order/ncf/j2e-translation-services/premium-translation?source=website"  | //*[@id="prospect"]/div/div/div/div/div/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[21]/div[4]/app-lynk/a | "/order/ncf/j2e-translation-services/japan-tl-plus-scientific-editing"    | //*[@id="prospect"]/div/div/div/div/div/button | "btn-primary-blue" |

    @sanity
    Scenario Outline: I expect to open order page on forms on clicking on pricing CTA on compare translation page pes & ses
        When I click on the element <path>
        Then I expect that element /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/h2 has the class "text-center"
        Then I click on the element <tabPath>
        Then I expect that element <formCTAPath> has the link <formCTAPathLink>
        Then I click on the element <formCTAPath>
        Then I expect that element <eosElementPath> has the class <eosElementClass>
        And I should go back to the previous page
        @jpn
        Examples:
            | path                                                                                                                 | tabPath                                                                                                                  | formCTAPath                                                                                                                        | formCTAPathLink                                                                                                                                     | eosElementPath                                                                                                                                                     | eosElementClass    |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[2] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/standard-translation?source=website"                                                                           | //*[@id="prospect"]/div/div/div/div/div/button                                                                                                                     | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[3] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/standard-translation?source=website"                                                                           | //*[@id="prospect"]/div/div/div/div/div/button                                                                                                                     | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[4] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/standard-translation?source=website"                                                                           | //*[@id="prospect"]/div/div/div/div/div/button                                                                                                                     | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[5] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div/app-lynk/a    | "/order/ncf/j2e-translation-services/japanese-custom-translation/document/plan/add-on/information?source=website&loop=enter-large-wc&addonskip=yes" | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[2]/app-phoenix-information/div[2]/div/div/div[7]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[1] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/standard-translation?source=website"                                                                           | //*[@id="prospect"]/div/div/div/div/div/button                                                                                                                     | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[1] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/premium-translation?source=website"                                                                            | //*[@id="prospect"]/div/div/div/div/div/button                                                                                                                     | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[2] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/premium-translation?source=website"                                                                            | //*[@id="prospect"]/div/div/div/div/div/button                                                                                                                     | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[3] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/premium-translation?source=website"                                                                            | //*[@id="prospect"]/div/div/div/div/div/button                                                                                                                     | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[4] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/premium-translation?source=website"                                                                            | //*[@id="prospect"]/div/div/div/div/div/button                                                                                                                     | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[5] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div/app-lynk/a    | "/order/ncf/j2e-translation-services/japanese-custom-translation/document/plan/add-on/information?source=website"                                   | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[2]/app-phoenix-information/div[2]/div/div/div[7]/div[2]/button | "btn-primary-blue" |

        @chn
        Examples:
            | path                                                                                                                 | tabPath                                                                                                                  | formCTAPath                                                                                                                        | formCTAPathLink                                                                                                 | eosElementPath                                                                                                                                                             | eosElementClass    |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[1] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-level-1?source=website"                          | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-document/div/section/div[1]/div[1]/div[1]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[2] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-level-1?source=website"                          | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-document/div/section/div[1]/div[1]/div[1]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[3] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-level-1?source=website"                          | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-document/div/section/div[1]/div[1]/div[1]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[4] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-level-1?source=website"                          | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-document/div/section/div[1]/div[1]/div[1]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[5] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-level-1?source=website"                          | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-document/div/section/div[1]/div[1]/div[1]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[1]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[6] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div/app-lynk/a    | "/order/ncf/translation-services/simplified-chinese-to-english-level-1?source=website"                          | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-document/div/section/div[1]/div[1]/div[1]/div[2]/button | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[1] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing?source=website"      | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-add-on/div[1]/div/div[2]/button                         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[2] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing?source=website"      | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-add-on/div[1]/div/div[2]/button                         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[3] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing?source=website"      | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-add-on/div[1]/div/div[2]/button                         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[4] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing?source=website"      | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-add-on/div[1]/div/div[2]/button                         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[5] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing?source=website"      | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-add-on/div[1]/div/div[2]/button                         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[2]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[6] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div/app-lynk/a    | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing?source=website"      | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-add-on/div[1]/div/div[2]/button                         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[3]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[1] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing-plus?source=website" | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[2]/app-phoenix-information/div[2]/div/div/div[5]/div[2]/button         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[3]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[2] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing-plus?source=website" | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[2]/app-phoenix-information/div[2]/div/div/div[5]/div[2]/button         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[3]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[3] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing-plus?source=website" | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[2]/app-phoenix-information/div[2]/div/div/div[5]/div[2]/button         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[3]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[4] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing-plus?source=website" | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[2]/app-phoenix-information/div[2]/div/div/div[5]/div[2]/button         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[3]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[5] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div[2]/app-lynk/a | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing-plus?source=website" | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[2]/app-phoenix-information/div[2]/div/div/div[5]/div[2]/button         | "btn-primary-blue" |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[5]/app-compare-block-information[3]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[1]/span[6] | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[3]/div/app-lynk/a    | "/order/ncf/translation-services/simplified-chinese-to-english-translation-premium-editing-plus?source=website" | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[2]/app-phoenix-information/div[2]/div/div/div[5]/div[2]/button         | "btn-primary-blue" |

    @sanity
    Scenario Outline: I expect to open order page on forms on clicking on pricing CTA on compare translation page pes plus
        When I click on the element <path>
        Then I expect that element <formCTAPath> has the link <formCTAPathLink>
        Then I click on the element <formCTAPath>
        Then I expect that element <eosElementPath> has the class <eosElementClass>
        And I should go back to the previous page
        @jpn
        Examples:
            | path                                                                                                                 | formCTAPath                                                                                                                        | formCTAPathLink                                                                       | eosElementPath                                                                                                                                                            | eosElementClass    |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[4]/app-compare-block-information[3]/div/app-lynk/a | /html/body/lib-dialog/div/div/app-modal-component-ruby/div/div/app-pricing-block-ruby/section/div/div/div/div[2]/div[2]/app-lynk/a | "/order/ncf/j2e-translation-services/japan-tl-plus-scientific-editing?source=website" | /html/body/app-root/ng-component/div/section/div/ng-component/div/div/div[2]/div/div/div[1]/div/div[1]/app-phoenix-plan/div/div/app-phoenix-plan-items/form/div[2]/button | "btn-primary-blue" |

    @chn
    Scenario: I expect to verify the h1 tags on compare translation page
        Then I expect the page to contain tagname h1 to be equal to count 1

    Scenario Outline: I expect to verify all links have the attribute with the required value
        Then I expect that element <element> has the attribute <attribute> with value <value>
        @chn
        Examples:
            | element                                                                                 | attribute | value    |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[20]/div[2]/app-lynk/a | rel       | nofollow |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[20]/div[3]/app-lynk/a | rel       | nofollow |
            | /html/body/app-root/ng-component/app-comparison-block/div/div/div[20]/div[4]/app-lynk/a | rel       | nofollow |